[book]
src = "src"

language = "en"
multilingual = false

title = "Data structures cheat sheet"
description = "The ultimate cheat sheet for data structures and algorithms."

authors = ["soyflourbread"]
